# !!! Place this file in ~/.config/specify/

[playlist_settings]
# Specify desired tempo [bpm]
target_tempo = 120

# Specify tolerable tempo range [bpm]
tempo_tolerance = 5

# Specify desired no. of tracks
playlist_length = 10

# Setting this to 'true' ensures selected tracks do not appear in any other playlist
exclude_existing_tracks = true

# 1 for five of your Top Tracks, 2 for a random selection of 5 of your Liked Songs
seed_source = 2
